apiVersion: v1
kind: ConfigMap
metadata:
  name: fluenbit-config
  namespace: monitoring
data:
  fluent-bit.conf: |
    [INPUT]
        Name                tail
        Tag                 nginx.*
        Path                /var/log/nginx/access.log
        Parser              nginx
        DB                  /var/log/flb_nginx.db
        Mem_Buf_Limit       5MB
        Skip_Long_Lines     On
        Refresh_Interval    10

    [OUTPUT]
        Name                loki
        Match               *
        Host                loki.monitoring.svc.cluster.local
        Port                3100
        Labels              log=nginx

    [OUTPUT]
        Name                stdout
        Match               *
  parsers.conf: |
    [PARSER]
        Name   nginx
        Format regex
        Regex  ^(?<remote>[^ ]*) - (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>[^ ]*) (?<path>[^ ]*) (?<protocol>[^"]*)" (?<status>[^ ]*) (?<size>[^ ]*) "(?<referer>[^"]*)" "(?<agent>[^"]*)"
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z
