apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        orgId: 1
        url: http://loki.monitoring.svc.cluster.local:3100
        basicAuth: false
        isDefault: true
        version: 1
        editable: false
  grafana.ini: |
    [server]
    root_url = http://grafana.monitoring.svc.cluster.local
    http_addr = 0.0.0.0
    http_port = 3000

    [dataproxy]
    logging = true
    timeout = 30

    [log]
    mode = console
    level = info

    [datasources]
    datasource_limit = 5000
